<?php

namespace App\Console\Commands;

use App\Models\Permission;
use App\Support\FilamentPermissionRegistry;
use Illuminate\Console\Attributes\Description;
use Illuminate\Console\Attributes\Signature;
use Illuminate\Console\Command;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Str;
use Symfony\Component\Finder\SplFileInfo;

#[Signature('biwms:permissions-cleanup {--dry-run : Report eligible old generated permissions without deleting them} {--force : Delete eligible permissions after safety checks}')]
#[Description('Report and optionally remove obsolete generated permission rows.')]
class BiwmsPermissionsCleanup extends Command
{
    private ?string $codeReferenceText = null;

    /**
     * Execute the console command.
     */
    public function handle(FilamentPermissionRegistry $registry): int
    {
        $dryRun = ! $this->option('force') || $this->option('dry-run');
        $currentSeederPermissions = collect($registry->generatedPermissionNames())
            ->merge($this->legacyCompatibilityPermissions())
            ->unique()
            ->values();

        $permissions = Permission::query()
            ->with('roles:id,name')
            ->where('guard_name', 'web')
            ->orderBy('name')
            ->get()
            ->filter(fn (Permission $permission): bool => $this->isOldGeneratedPermission($permission->name))
            ->values();

        $rows = $permissions->map(function (Permission $permission) use ($currentSeederPermissions): array {
            $nonSuperAdminRoles = $permission->roles
                ->reject(fn ($role): bool => $this->isSuperAdminRole((string) $role->name))
                ->pluck('name')
                ->values()
                ->all();

            $status = 'eligible';
            $reason = 'not generated, not legacy-compatible, not code-referenced, and not assigned outside Super Admin';

            if ($currentSeederPermissions->contains($permission->name)) {
                $status = 'protected';
                $reason = 'generated by current seeder or listed for legacy compatibility';
            } elseif ($this->isReferencedInCode($permission->name)) {
                $status = 'protected';
                $reason = 'referenced in code';
            } elseif ($nonSuperAdminRoles !== []) {
                $status = 'needs-confirmation';
                $reason = 'assigned to non-Super Admin role(s): '.implode(', ', $nonSuperAdminRoles);
            }

            return [
                'permission' => $permission,
                'name' => $permission->name,
                'status' => $status,
                'reason' => $reason,
            ];
        });

        $this->line($dryRun ? 'Dry run: no permissions will be deleted.' : 'Force mode: eligible permissions may be deleted.');
        $this->newLine();

        $this->table(
            ['Permission', 'Status', 'Reason'],
            $rows->map(fn (array $row): array => [$row['name'], $row['status'], $row['reason']])->all(),
        );

        if ($dryRun) {
            $this->summary($rows);

            return self::SUCCESS;
        }

        $deleted = 0;
        $skipped = 0;

        foreach ($rows as $row) {
            if ($row['status'] === 'protected') {
                $skipped++;

                continue;
            }

            if ($row['status'] === 'needs-confirmation' && ! $this->confirm("Remove {$row['name']} despite non-Super Admin role assignment?", false)) {
                $skipped++;

                continue;
            }

            $row['permission']->delete();
            $deleted++;
        }

        $this->info("Deleted {$deleted} old generated permission row(s).");
        $this->line("Skipped {$skipped} protected or unconfirmed permission row(s).");

        return self::SUCCESS;
    }

    private function isSuperAdminRole(string $roleName): bool
    {
        return in_array(Str::of($roleName)->lower()->replace(' ', '_')->toString(), ['super_admin'], true);
    }

    private function isOldGeneratedPermission(string $permission): bool
    {
        return (bool) preg_match('/^(view_any|view|create|update|delete|delete_any|restore|restore_any|force_delete|force_delete_any)_[a-z0-9_]+$/', $permission);
    }

    private function isReferencedInCode(string $permission): bool
    {
        return Str::contains($this->codeReferenceText(), $permission);
    }

    /**
     * @return Collection<int, SplFileInfo>
     */
    private function codeFiles(): Collection
    {
        return collect([
            app_path(),
            config_path(),
            database_path('seeders'),
            resource_path(),
            base_path('routes'),
            base_path('tests'),
        ])
            ->filter(fn (string $path): bool => File::exists($path))
            ->flatMap(fn (string $path): array => File::allFiles($path))
            ->filter(fn ($file): bool => in_array($file->getExtension(), ['php', 'blade.php'], true))
            ->values();
    }

    private function codeReferenceText(): string
    {
        if ($this->codeReferenceText !== null) {
            return $this->codeReferenceText;
        }

        return $this->codeReferenceText = $this->codeFiles()
            ->map(fn ($file): string => $file->getContents())
            ->implode("\n");
    }

    /**
     * @return Collection<int, string>
     */
    private function legacyCompatibilityPermissions(): Collection
    {
        $seeder = File::get(database_path('seeders/PermissionsTableSeeder.php'));

        return collect([
            ...$this->permissionArrayFromSeeder($seeder, 'legacyPermissions'),
            ...$this->permissionArrayFromSeeder($seeder, 'bcPermissions'),
        ])->unique()->values();
    }

    /**
     * @return array<int, string>
     */
    private function permissionArrayFromSeeder(string $seeder, string $variable): array
    {
        if (! preg_match('/\$'.$variable.'\s*=\s*(\[[\s\S]*?\]);/', $seeder, $matches)) {
            return [];
        }

        /** @var array<int, string> $permissions */
        $permissions = eval('return '.$matches[1].';');

        return array_values(array_filter($permissions, is_string(...)));
    }

    /**
     * @param  Collection<int, array{status: string}>  $rows
     */
    private function summary(Collection $rows): void
    {
        $this->newLine();
        $this->line('Summary');
        $this->line('Protected: '.$rows->where('status', 'protected')->count());
        $this->line('Needs confirmation: '.$rows->where('status', 'needs-confirmation')->count());
        $this->line('Eligible: '.$rows->where('status', 'eligible')->count());
    }
}
