<?php

namespace Database\Seeders;

use App\Models\Location;
use Illuminate\Database\Seeder;

class LocationSeeder extends Seeder
{
    public function run(): void
    {
        $locations = [
            // Main Distribution Center - Full WMS
            [
                'code' => 'MAIN',
                'name' => 'Main Distribution Center',
                'address' => '1000 Logistics Parkway, Industrial District, Chicago, IL 60601',
                'directed_put_away_and_pick' => true,
                'bin_mandatory' => true,
                'require_receive' => true,
                'require_shipment' => true,
                'require_put_away' => true,
                'require_pick' => true,
                'receipt_bin_code' => 'RECEIVE-01',
                'shipment_bin_code' => 'SHIP-01',
                'open_shop_floor_bin_code' => 'SHOP-01',
                'inbound_production_bin_code' => 'PROD-IN-01',
                'outbound_production_bin_code' => 'PROD-OUT-01',
                'adjustment_bin_code' => 'ADJUST-01',
                'blocked' => false,
            ],
            // East Coast Warehouse - Full WMS
            [
                'code' => 'EAST',
                'name' => 'East Coast Warehouse',
                'address' => '2500 Port Authority Drive, Newark, NJ 07114',
                'directed_put_away_and_pick' => true,
                'bin_mandatory' => true,
                'require_receive' => true,
                'require_shipment' => true,
                'require_put_away' => true,
                'require_pick' => true,
                'receipt_bin_code' => 'RCV-EAST',
                'shipment_bin_code' => 'SHP-EAST',
                'open_shop_floor_bin_code' => null,
                'inbound_production_bin_code' => null,
                'outbound_production_bin_code' => null,
                'adjustment_bin_code' => 'ADJ-EAST',
                'blocked' => false,
            ],
            // West Coast Warehouse - Full WMS
            [
                'code' => 'WEST',
                'name' => 'West Coast Warehouse',
                'address' => '3800 Harbor Boulevard, Long Beach, CA 90802',
                'directed_put_away_and_pick' => true,
                'bin_mandatory' => true,
                'require_receive' => true,
                'require_shipment' => true,
                'require_put_away' => true,
                'require_pick' => true,
                'receipt_bin_code' => 'RCV-WEST',
                'shipment_bin_code' => 'SHP-WEST',
                'open_shop_floor_bin_code' => null,
                'inbound_production_bin_code' => null,
                'outbound_production_bin_code' => null,
                'adjustment_bin_code' => 'ADJ-WEST',
                'blocked' => false,
            ],
            // Manufacturing Plant - Production focused
            [
                'code' => 'PLANT-01',
                'name' => 'Manufacturing Plant 1',
                'address' => '500 Factory Row, Detroit, MI 48207',
                'directed_put_away_and_pick' => true,
                'bin_mandatory' => true,
                'require_receive' => true,
                'require_shipment' => false,
                'require_put_away' => true,
                'require_pick' => true,
                'receipt_bin_code' => 'RAW-RCV',
                'shipment_bin_code' => null,
                'open_shop_floor_bin_code' => 'WIP-FLOOR',
                'inbound_production_bin_code' => 'WIP-IN',
                'outbound_production_bin_code' => 'FG-OUT',
                'adjustment_bin_code' => 'ADJ-PLANT',
                'blocked' => false,
            ],
            // Regional Warehouse - Basic WMS
            [
                'code' => 'REGION-S',
                'name' => 'Southern Regional Hub',
                'address' => '1200 Distribution Blvd, Atlanta, GA 30336',
                'directed_put_away_and_pick' => false,
                'bin_mandatory' => true,
                'require_receive' => false,
                'require_shipment' => false,
                'require_put_away' => false,
                'require_pick' => false,
                'receipt_bin_code' => 'INBOUND',
                'shipment_bin_code' => 'OUTBOUND',
                'open_shop_floor_bin_code' => null,
                'inbound_production_bin_code' => null,
                'outbound_production_bin_code' => null,
                'adjustment_bin_code' => 'COUNT',
                'blocked' => false,
            ],
            // Central Warehouse - Basic WMS
            [
                'code' => 'REGION-C',
                'name' => 'Central Regional Hub',
                'address' => '800 Freight Lane, Dallas, TX 75247',
                'directed_put_away_and_pick' => false,
                'bin_mandatory' => true,
                'require_receive' => false,
                'require_shipment' => false,
                'require_put_away' => false,
                'require_pick' => false,
                'receipt_bin_code' => 'INBOUND',
                'shipment_bin_code' => 'OUTBOUND',
                'open_shop_floor_bin_code' => null,
                'inbound_production_bin_code' => null,
                'outbound_production_bin_code' => null,
                'adjustment_bin_code' => 'COUNT',
                'blocked' => false,
            ],
            // Simple Storage - No bin control
            [
                'code' => 'STORE-A',
                'name' => 'Retail Store A - Backroom',
                'address' => '100 Mall Parkway, Store #100 Backroom',
                'directed_put_away_and_pick' => false,
                'bin_mandatory' => false,
                'require_receive' => false,
                'require_shipment' => false,
                'require_put_away' => false,
                'require_pick' => false,
                'receipt_bin_code' => null,
                'shipment_bin_code' => null,
                'open_shop_floor_bin_code' => null,
                'inbound_production_bin_code' => null,
                'outbound_production_bin_code' => null,
                'adjustment_bin_code' => null,
                'blocked' => false,
            ],
            // Simple Storage - No bin control
            [
                'code' => 'STORE-B',
                'name' => 'Retail Store B - Backroom',
                'address' => '200 Shopping Center Drive, Store #200 Backroom',
                'directed_put_away_and_pick' => false,
                'bin_mandatory' => false,
                'require_receive' => false,
                'require_shipment' => false,
                'require_put_away' => false,
                'require_pick' => false,
                'receipt_bin_code' => null,
                'shipment_bin_code' => null,
                'open_shop_floor_bin_code' => null,
                'inbound_production_bin_code' => null,
                'outbound_production_bin_code' => null,
                'adjustment_bin_code' => null,
                'blocked' => false,
            ],
            // Cold Storage - Full WMS with special handling
            [
                'code' => 'COLD-01',
                'name' => 'Cold Storage Facility',
                'address' => '1500 Refrigerated Way, Milwaukee, WI 53221',
                'directed_put_away_and_pick' => true,
                'bin_mandatory' => true,
                'require_receive' => true,
                'require_shipment' => true,
                'require_put_away' => true,
                'require_pick' => true,
                'receipt_bin_code' => 'COLD-RCV',
                'shipment_bin_code' => 'COLD-SHP',
                'open_shop_floor_bin_code' => null,
                'inbound_production_bin_code' => null,
                'outbound_production_bin_code' => null,
                'adjustment_bin_code' => 'COLD-ADJ',
                'blocked' => false,
            ],
            // Hazardous Materials - Full WMS with restrictions
            [
                'code' => 'HAZMAT',
                'name' => 'Hazmat Storage Facility',
                'address' => '2000 Industrial Safety Road, Remote Site, TX 77001',
                'directed_put_away_and_pick' => true,
                'bin_mandatory' => true,
                'require_receive' => true,
                'require_shipment' => true,
                'require_put_away' => true,
                'require_pick' => true,
                'receipt_bin_code' => 'HAZ-RCV',
                'shipment_bin_code' => 'HAZ-SHP',
                'open_shop_floor_bin_code' => null,
                'inbound_production_bin_code' => null,
                'outbound_production_bin_code' => null,
                'adjustment_bin_code' => 'HAZ-ADJ',
                'blocked' => false,
            ],
            // Quarantine/Quality Control
            [
                'code' => 'QUAR',
                'name' => 'Quarantine / Quality Control',
                'address' => 'Main DC - Quarantine Wing, Chicago, IL 60601',
                'directed_put_away_and_pick' => false,
                'bin_mandatory' => true,
                'require_receive' => true,
                'require_shipment' => false,
                'require_put_away' => false,
                'require_pick' => false,
                'receipt_bin_code' => 'QC-HOLD',
                'shipment_bin_code' => null,
                'open_shop_floor_bin_code' => null,
                'inbound_production_bin_code' => null,
                'outbound_production_bin_code' => null,
                'adjustment_bin_code' => 'QC-ADJ',
                'blocked' => false,
            ],
            // Returns Processing
            [
                'code' => 'RETURNS',
                'name' => 'Returns Processing Center',
                'address' => '300 Returns Lane, Indianapolis, IN 46201',
                'directed_put_away_and_pick' => false,
                'bin_mandatory' => true,
                'require_receive' => true,
                'require_shipment' => false,
                'require_put_away' => false,
                'require_pick' => true,
                'receipt_bin_code' => 'RET-RCV',
                'shipment_bin_code' => 'RET-SHP',
                'open_shop_floor_bin_code' => null,
                'inbound_production_bin_code' => null,
                'outbound_production_bin_code' => null,
                'adjustment_bin_code' => 'RET-ADJ',
                'blocked' => false,
            ],
            // Drop Ship Virtual Location
            [
                'code' => 'DROP-SHIP',
                'name' => 'Drop Ship Location',
                'address' => 'Virtual - Direct to Customer',
                'directed_put_away_and_pick' => false,
                'bin_mandatory' => false,
                'require_receive' => false,
                'require_shipment' => false,
                'require_put_away' => false,
                'require_pick' => false,
                'receipt_bin_code' => null,
                'shipment_bin_code' => null,
                'open_shop_floor_bin_code' => null,
                'inbound_production_bin_code' => null,
                'outbound_production_bin_code' => null,
                'adjustment_bin_code' => null,
                'blocked' => false,
            ],
            // In Transit
            [
                'code' => 'IN-TRANSIT',
                'name' => 'In Transit',
                'address' => 'Virtual - Goods in Transit',
                'directed_put_away_and_pick' => false,
                'bin_mandatory' => false,
                'require_receive' => false,
                'require_shipment' => false,
                'require_put_away' => false,
                'require_pick' => false,
                'receipt_bin_code' => null,
                'shipment_bin_code' => null,
                'open_shop_floor_bin_code' => null,
                'inbound_production_bin_code' => null,
                'outbound_production_bin_code' => null,
                'adjustment_bin_code' => null,
                'blocked' => false,
            ],
            // Blocked/Decommissioned
            [
                'code' => 'OLD-DC',
                'name' => 'Old Distribution Center (Closed)',
                'address' => 'Formerly 500 Old Warehouse Road',
                'directed_put_away_and_pick' => false,
                'bin_mandatory' => false,
                'require_receive' => false,
                'require_shipment' => false,
                'require_put_away' => false,
                'require_pick' => false,
                'receipt_bin_code' => null,
                'shipment_bin_code' => null,
                'open_shop_floor_bin_code' => null,
                'inbound_production_bin_code' => null,
                'outbound_production_bin_code' => null,
                'adjustment_bin_code' => null,
                'blocked' => true,
            ],
        ];

        foreach ($locations as $location) {
            Location::firstOrCreate(
                ['code' => $location['code']],
                $location
            );
        }

        $this->command->info('Locations seeded successfully!');
        $this->command->info('Total: '.count($locations).' locations');
        $this->command->info('Active: '.collect($locations)->where('blocked', false)->count());
        $this->command->info('Blocked: '.collect($locations)->where('blocked', true)->count());
        $this->command->info('Full WMS: '.collect($locations)->where('directed_put_away_and_pick', true)->count());
        $this->command->info('Basic Bin: '.collect($locations)->where('bin_mandatory', true)->where('directed_put_away_and_pick', false)->count());
        $this->command->info('No Bin Control: '.collect($locations)->where('bin_mandatory', false)->count());
    }
}
