<?php

namespace Database\Seeders;

use App\Models\Permission;
use App\Models\Role;
use Illuminate\Database\Seeder;
use Spatie\Permission\PermissionRegistrar;

class RolePermissionSetSeeder extends Seeder
{
    public function run(): void
    {
        app(PermissionRegistrar::class)->forgetCachedPermissions();

        $matrix = [
            'sales-representative' => [
                'sales.customer.view_any', 'sales.customer.view', 'sales.customer.create', 'sales.customer.update',
                'sales.referrer.view_any', 'sales.referrer.view',
                'sales.customer_referral.view_any', 'sales.customer_referral.view',
                'sales.referral_commission_setting.view_any', 'sales.referral_commission_setting.view',
                'sales.referral_commission_plan.view_any', 'sales.referral_commission_plan.view',
                'sales.referrer_commission_plan_assignment.view_any', 'sales.referrer_commission_plan_assignment.view',
                'sales.item.view_any', 'sales.item.view',
                'sales.quote.view_any', 'sales.quote.view', 'sales.quote.create', 'sales.quote.update', 'sales.quote.convert',
                'sales.order.view_any', 'sales.order.view', 'sales.order.create', 'sales.order.update',
                'sales.invoice.view_any', 'sales.invoice.view',
            ],
            'sales-manager' => [
                'sales.customer.view_any', 'sales.customer.view', 'sales.customer.create', 'sales.customer.update', 'sales.customer.delete',
                'sales.customer_contact.view_any', 'sales.customer_contact.view', 'sales.customer_contact.create', 'sales.customer_contact.update', 'sales.customer_contact.delete',
                'sales.referrer.view_any', 'sales.referrer.view', 'sales.referrer.create', 'sales.referrer.update', 'sales.referrer.delete', 'sales.referrer.delete_any', 'sales.referrer.restore', 'sales.referrer.restore_any',
                'sales.customer_referral.view_any', 'sales.customer_referral.view', 'sales.customer_referral.create', 'sales.customer_referral.update', 'sales.customer_referral.delete', 'sales.customer_referral.assign', 'sales.customer_referral.change', 'sales.customer_referral.approve', 'sales.customer_referral.suspend', 'sales.customer_referral.reactivate', 'sales.customer_referral.end', 'sales.customer_referral.cancel',
                'sales.referral_commission_setting.view_any', 'sales.referral_commission_setting.view', 'sales.referral_commission_setting.create', 'sales.referral_commission_setting.update', 'sales.referral_commission_setting.manage',
                'sales.referral_commission_plan.view_any', 'sales.referral_commission_plan.view', 'sales.referral_commission_plan.create', 'sales.referral_commission_plan.update', 'sales.referral_commission_plan.activate', 'sales.referral_commission_plan.inactivate',
                'sales.referrer_commission_plan_assignment.view_any', 'sales.referrer_commission_plan_assignment.view', 'sales.referrer_commission_plan_assignment.create', 'sales.referrer_commission_plan_assignment.assign', 'sales.referrer_commission_plan_assignment.change', 'sales.referrer_commission_plan_assignment.end', 'sales.referrer_commission_plan_assignment.cancel',
                'sales.item.view_any', 'sales.item.view',
                'sales.quote.view_any', 'sales.quote.view', 'sales.quote.create', 'sales.quote.update', 'sales.quote.delete', 'sales.quote.approve', 'sales.quote.convert',
                'sales.order.view_any', 'sales.order.view', 'sales.order.create', 'sales.order.update', 'sales.order.delete', 'sales.order.approve', 'sales.order.post',
                'sales.invoice.view_any', 'sales.invoice.view',
            ],
            'finance-accountant' => [
                'finance.payment.view_any', 'finance.payment.view', 'finance.payment.create', 'finance.payment.update',
                'finance.payment.post', 'finance.payment.apply', 'finance.payment.reconcile',
                'finance.petty_cash_voucher.view_any', 'finance.petty_cash_voucher.view', 'finance.petty_cash_voucher.create', 'finance.petty_cash_voucher.update',
                'finance.petty_cash_voucher.approve', 'finance.petty_cash_voucher.post',
                'finance.bank_account.view_any', 'finance.bank_account.view',
                'finance.general_journal_batch.view_any', 'finance.general_journal_batch.view', 'finance.general_journal_batch.create', 'finance.general_journal_batch.update',
                'finance.currency_adjustment_ledger.view_any', 'finance.currency_adjustment_ledger.view',
                'finance.customer_ledger_entry.view_any', 'finance.customer_ledger_entry.view',
                'finance.report.view',
                'fixed_asset.view_any', 'fixed_asset.view', 'fixed_asset.depreciate',
                'sales.invoice.view_any', 'sales.invoice.view', 'sales.invoice.update', 'sales.invoice.post',
                'sales.order.view_any', 'sales.order.view',
            ],
            'finance-manager' => [
                'finance.payment.view_any', 'finance.payment.view', 'finance.payment.create', 'finance.payment.update', 'finance.payment.delete',
                'finance.payment.post', 'finance.payment.apply', 'finance.payment.reconcile', 'finance.payment.void',
                'finance.petty_cash_voucher.view_any', 'finance.petty_cash_voucher.view', 'finance.petty_cash_voucher.create', 'finance.petty_cash_voucher.update', 'finance.petty_cash_voucher.delete',
                'finance.petty_cash_voucher.approve', 'finance.petty_cash_voucher.post', 'finance.petty_cash_voucher.cancel',
                'finance.bank_account.view_any', 'finance.bank_account.view', 'finance.bank_account.create', 'finance.bank_account.update',
                'finance.general_journal_batch.view_any', 'finance.general_journal_batch.view', 'finance.general_journal_batch.create', 'finance.general_journal_batch.update', 'finance.general_journal_batch.delete',
                'finance.currency_adjustment_ledger.view_any', 'finance.currency_adjustment_ledger.view', 'finance.currency_adjustment_ledger.create', 'finance.currency_adjustment_ledger.update',
                'finance.customer_ledger_entry.view_any', 'finance.customer_ledger_entry.view',
                'finance.report.view',
                'fixed_asset.view_any', 'fixed_asset.view', 'fixed_asset.create', 'fixed_asset.update', 'fixed_asset.acquire', 'fixed_asset.depreciate', 'fixed_asset.dispose',
                'sales.invoice.view_any', 'sales.invoice.view', 'sales.invoice.create', 'sales.invoice.update', 'sales.invoice.delete', 'sales.invoice.post',
                'sales.referrer.view_any', 'sales.referrer.view',
                'sales.customer_referral.view_any', 'sales.customer_referral.view',
                'sales.referral_commission_setting.view_any', 'sales.referral_commission_setting.view',
                'sales.referral_commission_plan.view_any', 'sales.referral_commission_plan.view',
                'sales.referrer_commission_plan_assignment.view_any', 'sales.referrer_commission_plan_assignment.view',
                'sales.order.view_any', 'sales.order.view',
            ],
            'purchasing-agent' => [
                'procurement.vendor.view_any', 'procurement.vendor.view',
                'procurement.purchase_quote.view_any', 'procurement.purchase_quote.view', 'procurement.purchase_quote.create', 'procurement.purchase_quote.update',
                'procurement.purchase_order.view_any', 'procurement.purchase_order.view', 'procurement.purchase_order.create', 'procurement.purchase_order.update',
                'procurement.purchase_receipt.view_any', 'procurement.purchase_receipt.view', 'procurement.purchase_receipt.create',
                'procurement.purchase_invoice.view_any', 'procurement.purchase_invoice.view',
                'procurement.purchase_credit_memo.view_any', 'procurement.purchase_credit_memo.view', 'procurement.purchase_credit_memo.create',
                'procurement.blanket_order.view_any', 'procurement.blanket_order.view',
                'sales.item.view_any', 'sales.item.view',
            ],
            'purchasing-manager' => [
                'procurement.vendor.view_any', 'procurement.vendor.view', 'procurement.vendor.create', 'procurement.vendor.update', 'procurement.vendor.delete',
                'procurement.purchase_quote.view_any', 'procurement.purchase_quote.view', 'procurement.purchase_quote.create', 'procurement.purchase_quote.update', 'procurement.purchase_quote.delete',
                'procurement.purchase_order.view_any', 'procurement.purchase_order.view', 'procurement.purchase_order.create', 'procurement.purchase_order.update', 'procurement.purchase_order.delete',
                'procurement.purchase_receipt.view_any', 'procurement.purchase_receipt.view', 'procurement.purchase_receipt.create', 'procurement.purchase_receipt.update',
                'procurement.purchase_invoice.view_any', 'procurement.purchase_invoice.view', 'procurement.purchase_invoice.create', 'procurement.purchase_invoice.update',
                'procurement.purchase_credit_memo.view_any', 'procurement.purchase_credit_memo.view', 'procurement.purchase_credit_memo.create', 'procurement.purchase_credit_memo.update', 'procurement.purchase_credit_memo.delete',
                'procurement.blanket_order.view_any', 'procurement.blanket_order.view', 'procurement.blanket_order.create', 'procurement.blanket_order.update', 'procurement.blanket_order.delete',
                'sales.item.view_any', 'sales.item.view',
            ],
            'warehouse-worker' => [
                'warehouse.receipt.view_any', 'warehouse.receipt.view', 'warehouse.receipt.create',
                'warehouse.activity.view_any', 'warehouse.activity.view', 'warehouse.activity.create',
                'warehouse.putaway.view_any', 'warehouse.putaway.view', 'warehouse.putaway.create',
                'warehouse.shipment.view_any', 'warehouse.shipment.view', 'warehouse.shipment.create',
                'sales.item.view_any', 'sales.item.view',
                'sales.order.view_any', 'sales.order.view',
            ],
            'warehouse-manager' => [
                'warehouse.receipt.view_any', 'warehouse.receipt.view', 'warehouse.receipt.create', 'warehouse.receipt.update', 'warehouse.receipt.delete',
                'warehouse.activity.view_any', 'warehouse.activity.view', 'warehouse.activity.create', 'warehouse.activity.update', 'warehouse.activity.delete',
                'warehouse.putaway.view_any', 'warehouse.putaway.view', 'warehouse.putaway.create', 'warehouse.putaway.update', 'warehouse.putaway.delete',
                'warehouse.shipment.view_any', 'warehouse.shipment.view', 'warehouse.shipment.create', 'warehouse.shipment.update', 'warehouse.shipment.delete',
                'sales.item.view_any', 'sales.item.view', 'sales.item.update',
                'sales.order.view_any', 'sales.order.view', 'sales.order.post',
            ],
            'factory-operator' => [
                'factory.production_order.planned.view_any', 'factory.production_order.planned.view',
                'factory.production_order.view_any', 'factory.production_order.view',
                'sales.item.view_any', 'sales.item.view',
            ],
            'factory-manager' => [
                'factory.production_order.view_any', 'factory.production_order.view', 'factory.production_order.create', 'factory.production_order.update', 'factory.production_order.delete', 'factory.production_order.post_output', 'factory.production_order.finish', 'factory.production_order.post',
                'factory.production_bom.view_any', 'factory.production_bom.view', 'factory.production_bom.create', 'factory.production_bom.update', 'factory.production_bom.delete',
                'factory.production_bom_version.view_any', 'factory.production_bom_version.view', 'factory.production_bom_version.create', 'factory.production_bom_version.update', 'factory.production_bom_version.delete',
                'factory.routing.view_any', 'factory.routing.view', 'factory.routing.create', 'factory.routing.update', 'factory.routing.delete',
                'factory.routing_version.view_any', 'factory.routing_version.view', 'factory.routing_version.create', 'factory.routing_version.update', 'factory.routing_version.delete',
                'factory.machine_center.view_any', 'factory.machine_center.view', 'factory.machine_center.create', 'factory.machine_center.update', 'factory.machine_center.delete',
                'factory.work_center.view_any', 'factory.work_center.view', 'factory.work_center.create', 'factory.work_center.update', 'factory.work_center.delete',
                'factory.work_center_group.view_any', 'factory.work_center_group.view', 'factory.work_center_group.create', 'factory.work_center_group.update', 'factory.work_center_group.delete',
                'factory.overhead_cost_category.view_any', 'factory.overhead_cost_category.view', 'factory.overhead_cost_category.create', 'factory.overhead_cost_category.update', 'factory.overhead_cost_category.delete',
                'factory.actual_overhead_cost.view_any', 'factory.actual_overhead_cost.view', 'factory.actual_overhead_cost.create', 'factory.actual_overhead_cost.update', 'factory.actual_overhead_cost.delete',
                'factory.report.view',
                'sales.item.view_any', 'sales.item.view', 'sales.item.update',
            ],
            'hr-officer' => [
                'hr.employee.view_any', 'hr.employee.view', 'hr.employee.create', 'hr.employee.update',
                'hr.attendance.view_any', 'hr.attendance.view', 'hr.attendance.create', 'hr.attendance.update', 'hr.attendance.clock',
                'hr.attendance_clock.use', 'hr.my_attendance.view', 'hr.attendance_report.view',
                'hr.attendance_register.view_any', 'hr.attendance_register.view',
                'hr.attendance_event.view_any', 'hr.attendance_event.view', 'hr.attendance_event.create',
                'hr.attendance_correction.view_any', 'hr.attendance_correction.view', 'hr.attendance_correction.create', 'hr.attendance_correction.update',
                'hr.overtime_approval.view_any', 'hr.overtime_approval.view', 'hr.overtime_approval.create', 'hr.overtime_approval.update',
                'hr.attendance_review_period.view_any', 'hr.attendance_review_period.view',
                'hr.attendance_review_item.view_any', 'hr.attendance_review_item.view', 'hr.attendance_review_item.view_own', 'hr.attendance_review_item.view_team',
                'hr.workforce_roster_period.view_any', 'hr.workforce_roster_period.view',
                'hr.workforce_roster_assignment.view_any', 'hr.workforce_roster_assignment.view',
                'hr.workforce_rotation_template.view_any', 'hr.workforce_rotation_template.view',
                'hr.workforce_rotation_assignment.view_any', 'hr.workforce_rotation_assignment.view',
                'hr.workforce_staffing_requirement.view_any', 'hr.workforce_staffing_requirement.view',
                'hr.workforce_roster_role.view_any', 'hr.workforce_roster_role.view',
                'hr.employee_work_availability.view_any', 'hr.employee_work_availability.view',
                'hr.shift_swap_request.view_any', 'hr.shift_swap_request.view', 'hr.shift_swap_request.accept',
                'hr.shift_replacement.view_any', 'hr.shift_replacement.view',
                'hr.workforce_roster_history.view_any', 'hr.workforce_roster_history.view',
                'hr.workforce_roster_conflict.view', 'hr.workforce_coverage_report.view',
                'hr.my_roster.view', 'hr.my_availability.view', 'hr.my_availability.create', 'hr.my_shift_swap.view', 'hr.my_shift_swap.create',
                'hr.performance_appraisal_cycle.view_any', 'hr.performance_appraisal_cycle.view',
                'hr.performance_appraisal_template.view_any', 'hr.performance_appraisal_template.view',
                'hr.performance_rating_scale.view_any', 'hr.performance_rating_scale.view',
                'hr.performance_competency_framework.view_any', 'hr.performance_competency_framework.view',
                'hr.performance_competency.view_any', 'hr.performance_competency.view',
                'hr.performance_goal_plan.view_any', 'hr.performance_goal_plan.view',
                'hr.performance_goal.view_any', 'hr.performance_goal.view',
                'hr.performance_appraisal.view_any', 'hr.performance_appraisal.view',
                'hr.performance_development_plan.view_any', 'hr.performance_development_plan.view',
                'hr.performance_improvement_plan.view_any', 'hr.performance_improvement_plan.view',
                'hr.performance_probation_review.view_any', 'hr.performance_probation_review.view',
                'hr.performance_appraisal_dispute.view_any', 'hr.performance_appraisal_dispute.view',
                'hr.performance_recommendation.view_any', 'hr.performance_recommendation.view',
                'hr.performance_history.view',
                'hr.performance_report.view',
                'hr.team_performance.view', 'hr.team_performance.assess',
                'hr.my_performance.view', 'hr.my_goal.view', 'hr.my_goal.create', 'hr.my_goal.update',
                'hr.my_self_assessment.submit', 'hr.my_appraisal.acknowledge', 'hr.my_appraisal.dispute',
                'hr.my_development_plan.view', 'hr.my_performance_improvement_plan.view',
                'hr.recruitment_requisition.view_any', 'hr.recruitment_requisition.view', 'hr.recruitment_requisition.create', 'hr.recruitment_requisition.update', 'hr.recruitment_requisition.submit',
                'hr.recruitment_vacancy.view_any', 'hr.recruitment_vacancy.view',
                'hr.recruitment_job_posting.view_any', 'hr.recruitment_job_posting.view',
                'hr.recruitment_candidate.view_any', 'hr.recruitment_candidate.view', 'hr.recruitment_candidate.create', 'hr.recruitment_candidate.update',
                'hr.recruitment_application.view_any', 'hr.recruitment_application.view', 'hr.recruitment_application.create', 'hr.recruitment_application.update', 'hr.recruitment_application.advance',
                'hr.recruitment_screening.view_any', 'hr.recruitment_screening.view', 'hr.recruitment_screening.create', 'hr.recruitment_screening.update',
                'hr.recruitment_assessment.view_any', 'hr.recruitment_assessment.view',
                'hr.recruitment_interview.view_any', 'hr.recruitment_interview.view', 'hr.recruitment_interview.create', 'hr.recruitment_interview.update', 'hr.recruitment_interview.score',
                'hr.recruitment_selection_review.view_any', 'hr.recruitment_selection_review.view',
                'hr.recruitment_offer.view_any', 'hr.recruitment_offer.view',
                'hr.recruitment_pre_employment_check.view_any', 'hr.recruitment_pre_employment_check.view',
                'hr.recruitment_onboarding_plan.view_any', 'hr.recruitment_onboarding_plan.view',
                'hr.recruitment_onboarding_task.view_any', 'hr.recruitment_onboarding_task.view', 'hr.recruitment_onboarding_task.complete',
                'hr.recruitment_report.view', 'hr.recruitment_history.view',
                'hr.team_recruitment.view', 'hr.team_recruitment.review',
                'hr.my_onboarding.view', 'hr.my_onboarding.update', 'hr.my_probation_status.view', 'hr.my_confirmation_status.view',
                'payroll.attendance_batch.view_any', 'payroll.attendance_batch.view',
                'payroll.attendance_adjustment.view_any', 'payroll.attendance_adjustment.view',
                'hr.employee_shift.view_any', 'hr.employee_shift.view',
                'hr.work_schedule.view_any', 'hr.work_schedule.view',
                'hr.payroll_period.view_any', 'hr.payroll_period.view', 'hr.payroll_period.create', 'hr.payroll_period.update',
                'hr.payroll_document.view_any', 'hr.payroll_document.view', 'hr.payroll_document.create', 'hr.payroll_document.update',
                'hr.employee_payslip.view_any', 'hr.employee_payslip.view', 'hr.employee_payslip.generate', 'hr.employee_payslip.download', 'hr.employee_payslip.print',
                'hr.employee_payslip_history.view_any', 'hr.employee_payslip_history.view',
                'hr.leave_type.view_any', 'hr.leave_type.view',
                'hr.leave_policy.view_any', 'hr.leave_policy.view',
                'hr.leave_entitlement.view_any', 'hr.leave_entitlement.view',
                'hr.leave_request.view_any', 'hr.leave_request.view', 'hr.leave_request.create', 'hr.leave_request.update', 'hr.leave_request.submit', 'hr.leave_request.cancel',
                'hr.leave_approval.approve', 'hr.leave_approval.reject',
                'hr.leave_balance.view', 'hr.leave_ledger.view_any', 'hr.leave_ledger.view', 'hr.leave_calendar.view',
                'hr.pay_code.view_any', 'hr.pay_code.view',
                'hr.payroll_posting_group.view_any', 'hr.payroll_posting_group.view',
            ],
            'hr-manager' => [
                'hr.employee.view_any', 'hr.employee.view', 'hr.employee.create', 'hr.employee.update', 'hr.employee.delete',
                'hr.attendance.view_any', 'hr.attendance.view', 'hr.attendance.create', 'hr.attendance.update', 'hr.attendance.delete', 'hr.attendance.approve', 'hr.attendance.reject', 'hr.attendance.clock',
                'hr.attendance_clock.use', 'hr.my_attendance.view', 'hr.attendance_report.view', 'hr.attendance_report.export',
                'hr.attendance_location.view_any', 'hr.attendance_location.view', 'hr.attendance_location.create', 'hr.attendance_location.update', 'hr.attendance_location.delete',
                'hr.attendance_device.view_any', 'hr.attendance_device.view', 'hr.attendance_device.create', 'hr.attendance_device.update', 'hr.attendance_device.delete',
                'hr.employee_shift.view_any', 'hr.employee_shift.view', 'hr.employee_shift.create', 'hr.employee_shift.update', 'hr.employee_shift.delete',
                'hr.work_schedule.view_any', 'hr.work_schedule.view', 'hr.work_schedule.create', 'hr.work_schedule.update', 'hr.work_schedule.delete',
                'hr.attendance_register.view_any', 'hr.attendance_register.view',
                'hr.attendance_event.view_any', 'hr.attendance_event.view', 'hr.attendance_event.create',
                'hr.attendance_correction.view_any', 'hr.attendance_correction.view', 'hr.attendance_correction.create', 'hr.attendance_correction.update', 'hr.attendance_correction.delete', 'hr.attendance_correction.approve', 'hr.attendance_correction.reject',
                'hr.overtime_approval.view_any', 'hr.overtime_approval.view', 'hr.overtime_approval.create', 'hr.overtime_approval.update', 'hr.overtime_approval.delete', 'hr.overtime_approval.approve', 'hr.overtime_approval.reject',
                'hr.attendance_review_period.view_any', 'hr.attendance_review_period.view', 'hr.attendance_review_period.create', 'hr.attendance_review_period.update', 'hr.attendance_review_period.delete',
                'hr.attendance_review_period.open', 'hr.attendance_review_period.submit', 'hr.attendance_review_period.approve', 'hr.attendance_review_period.lock', 'hr.attendance_review_period.reopen', 'hr.attendance_review_period.export',
                'hr.attendance_review_item.view_any', 'hr.attendance_review_item.view', 'hr.attendance_review_item.create', 'hr.attendance_review_item.update', 'hr.attendance_review_item.delete',
                'hr.attendance_review_item.view_own', 'hr.attendance_review_item.view_team', 'hr.attendance_review_item.acknowledge', 'hr.attendance_review_item.resolve', 'hr.attendance_review_item.waive', 'hr.attendance_review_item.escalate', 'hr.attendance_review_item.approve_payroll_impact',
                'hr.workforce_roster_period.view_any', 'hr.workforce_roster_period.view', 'hr.workforce_roster_period.create', 'hr.workforce_roster_period.update', 'hr.workforce_roster_period.delete',
                'hr.workforce_roster_period.generate', 'hr.workforce_roster_period.submit', 'hr.workforce_roster_period.publish', 'hr.workforce_roster_period.close', 'hr.workforce_roster_period.reopen',
                'hr.workforce_roster_assignment.view_any', 'hr.workforce_roster_assignment.view', 'hr.workforce_roster_assignment.create', 'hr.workforce_roster_assignment.update', 'hr.workforce_roster_assignment.delete',
                'hr.workforce_roster_assignment.cancel', 'hr.workforce_roster_assignment.replace',
                'hr.workforce_rotation_template.view_any', 'hr.workforce_rotation_template.view', 'hr.workforce_rotation_template.create', 'hr.workforce_rotation_template.update', 'hr.workforce_rotation_template.delete',
                'hr.workforce_rotation_assignment.view_any', 'hr.workforce_rotation_assignment.view', 'hr.workforce_rotation_assignment.create', 'hr.workforce_rotation_assignment.update', 'hr.workforce_rotation_assignment.delete',
                'hr.workforce_staffing_requirement.view_any', 'hr.workforce_staffing_requirement.view', 'hr.workforce_staffing_requirement.create', 'hr.workforce_staffing_requirement.update', 'hr.workforce_staffing_requirement.delete',
                'hr.workforce_roster_role.view_any', 'hr.workforce_roster_role.view', 'hr.workforce_roster_role.create', 'hr.workforce_roster_role.update', 'hr.workforce_roster_role.delete',
                'hr.employee_work_availability.view_any', 'hr.employee_work_availability.view', 'hr.employee_work_availability.create', 'hr.employee_work_availability.update', 'hr.employee_work_availability.delete',
                'hr.employee_work_availability.approve', 'hr.employee_work_availability.reject', 'hr.employee_work_availability.view_confidential',
                'hr.shift_swap_request.view_any', 'hr.shift_swap_request.view', 'hr.shift_swap_request.create', 'hr.shift_swap_request.update', 'hr.shift_swap_request.delete',
                'hr.shift_swap_request.accept', 'hr.shift_swap_request.approve', 'hr.shift_swap_request.reject', 'hr.shift_swap_request.cancel',
                'hr.shift_replacement.view_any', 'hr.shift_replacement.view', 'hr.shift_replacement.create', 'hr.shift_replacement.update', 'hr.shift_replacement.delete',
                'hr.shift_replacement.approve', 'hr.shift_replacement.reject', 'hr.shift_replacement.cancel',
                'hr.workforce_scheduling_rule.view_any', 'hr.workforce_scheduling_rule.view', 'hr.workforce_scheduling_rule.create', 'hr.workforce_scheduling_rule.update', 'hr.workforce_scheduling_rule.delete', 'hr.workforce_scheduling_rule.override',
                'hr.workforce_roster_history.view_any', 'hr.workforce_roster_history.view',
                'hr.workforce_roster_conflict.view', 'hr.workforce_coverage_report.view', 'hr.workforce_coverage_report.export',
                'hr.my_roster.view', 'hr.my_availability.view', 'hr.my_availability.create', 'hr.my_shift_swap.view', 'hr.my_shift_swap.create',
                'hr.performance_rating_scale.view_any', 'hr.performance_rating_scale.view', 'hr.performance_rating_scale.create', 'hr.performance_rating_scale.update', 'hr.performance_rating_scale.delete',
                'hr.performance_appraisal_cycle.view_any', 'hr.performance_appraisal_cycle.view', 'hr.performance_appraisal_cycle.create', 'hr.performance_appraisal_cycle.update', 'hr.performance_appraisal_cycle.delete',
                'hr.performance_appraisal_cycle.open', 'hr.performance_appraisal_cycle.complete', 'hr.performance_appraisal_cycle.close', 'hr.performance_appraisal_cycle.reopen',
                'hr.performance_appraisal_template.view_any', 'hr.performance_appraisal_template.view', 'hr.performance_appraisal_template.create', 'hr.performance_appraisal_template.update', 'hr.performance_appraisal_template.delete',
                'hr.performance_competency_framework.view_any', 'hr.performance_competency_framework.view', 'hr.performance_competency_framework.create', 'hr.performance_competency_framework.update', 'hr.performance_competency_framework.delete',
                'hr.performance_competency.view_any', 'hr.performance_competency.view', 'hr.performance_competency.create', 'hr.performance_competency.update', 'hr.performance_competency.delete',
                'hr.performance_position_competency.view_any', 'hr.performance_position_competency.view', 'hr.performance_position_competency.create', 'hr.performance_position_competency.update', 'hr.performance_position_competency.delete',
                'hr.performance_goal_plan.view_any', 'hr.performance_goal_plan.view', 'hr.performance_goal_plan.create', 'hr.performance_goal_plan.update', 'hr.performance_goal_plan.delete',
                'hr.performance_goal.view_any', 'hr.performance_goal.view', 'hr.performance_goal.create', 'hr.performance_goal.update', 'hr.performance_goal.delete', 'hr.performance_goal.approve', 'hr.performance_goal.revise',
                'hr.performance_appraisal.view_any', 'hr.performance_appraisal.view', 'hr.performance_appraisal.create', 'hr.performance_appraisal.update',
                'hr.performance_appraisal.self_assess', 'hr.performance_appraisal.manager_assess', 'hr.performance_appraisal.secondary_review', 'hr.performance_appraisal.moderate', 'hr.performance_appraisal.finalize', 'hr.performance_appraisal.reopen', 'hr.performance_appraisal.amend', 'hr.performance_appraisal.acknowledge',
                'hr.performance_appraisal_moderation_session.view_any', 'hr.performance_appraisal_moderation_session.view', 'hr.performance_appraisal_moderation_session.create', 'hr.performance_appraisal_moderation_session.update',
                'hr.performance_development_plan.view_any', 'hr.performance_development_plan.view', 'hr.performance_development_plan.create', 'hr.performance_development_plan.update', 'hr.performance_development_plan.delete',
                'hr.performance_improvement_plan.view_any', 'hr.performance_improvement_plan.view', 'hr.performance_improvement_plan.create', 'hr.performance_improvement_plan.update', 'hr.performance_improvement_plan.delete', 'hr.performance_improvement_plan.activate', 'hr.performance_improvement_plan.complete',
                'hr.performance_probation_review.view_any', 'hr.performance_probation_review.view', 'hr.performance_probation_review.create', 'hr.performance_probation_review.update', 'hr.performance_probation_review.delete', 'hr.performance_probation_review.decide',
                'hr.performance_appraisal_dispute.view_any', 'hr.performance_appraisal_dispute.view', 'hr.performance_appraisal_dispute.create', 'hr.performance_appraisal_dispute.update',
                'hr.performance_recommendation.view_any', 'hr.performance_recommendation.view', 'hr.performance_recommendation.create', 'hr.performance_recommendation.update',
                'hr.performance_history.view',
                'hr.performance_report.view', 'hr.performance_report.export',
                'hr.team_performance.view', 'hr.team_performance.assess',
                'hr.my_performance.view', 'hr.my_goal.view', 'hr.my_goal.create', 'hr.my_goal.update',
                'hr.my_self_assessment.submit', 'hr.my_appraisal.acknowledge', 'hr.my_appraisal.dispute',
                'hr.my_development_plan.view', 'hr.my_performance_improvement_plan.view',
                'hr.recruitment_requisition.view_any', 'hr.recruitment_requisition.view', 'hr.recruitment_requisition.create', 'hr.recruitment_requisition.update', 'hr.recruitment_requisition.delete',
                'hr.recruitment_requisition.submit', 'hr.recruitment_requisition.approve', 'hr.recruitment_requisition.reject', 'hr.recruitment_requisition.amend',
                'hr.recruitment_vacancy.view_any', 'hr.recruitment_vacancy.view', 'hr.recruitment_vacancy.create', 'hr.recruitment_vacancy.update', 'hr.recruitment_vacancy.delete', 'hr.recruitment_vacancy.open', 'hr.recruitment_vacancy.pause', 'hr.recruitment_vacancy.close',
                'hr.recruitment_job_posting.view_any', 'hr.recruitment_job_posting.view', 'hr.recruitment_job_posting.create', 'hr.recruitment_job_posting.update', 'hr.recruitment_job_posting.delete',
                'hr.recruitment_candidate.view_any', 'hr.recruitment_candidate.view', 'hr.recruitment_candidate.create', 'hr.recruitment_candidate.update', 'hr.recruitment_candidate.delete', 'hr.recruitment_candidate.archive', 'hr.recruitment_candidate.view_confidential',
                'hr.recruitment_application.view_any', 'hr.recruitment_application.view', 'hr.recruitment_application.create', 'hr.recruitment_application.update', 'hr.recruitment_application.delete', 'hr.recruitment_application.advance', 'hr.recruitment_application.reject', 'hr.recruitment_application.reopen',
                'hr.recruitment_screening_template.view_any', 'hr.recruitment_screening_template.view', 'hr.recruitment_screening_template.create', 'hr.recruitment_screening_template.update', 'hr.recruitment_screening_template.delete',
                'hr.recruitment_screening.view_any', 'hr.recruitment_screening.view', 'hr.recruitment_screening.create', 'hr.recruitment_screening.update', 'hr.recruitment_screening.delete', 'hr.recruitment_screening.override',
                'hr.recruitment_assessment.view_any', 'hr.recruitment_assessment.view', 'hr.recruitment_assessment.create', 'hr.recruitment_assessment.update', 'hr.recruitment_assessment.delete',
                'hr.recruitment_interview_panel.view_any', 'hr.recruitment_interview_panel.view', 'hr.recruitment_interview_panel.create', 'hr.recruitment_interview_panel.update', 'hr.recruitment_interview_panel.delete',
                'hr.recruitment_interview.view_any', 'hr.recruitment_interview.view', 'hr.recruitment_interview.create', 'hr.recruitment_interview.update', 'hr.recruitment_interview.delete', 'hr.recruitment_interview.score', 'hr.recruitment_interview.reopen_score',
                'hr.recruitment_interview_scorecard_template.view_any', 'hr.recruitment_interview_scorecard_template.view', 'hr.recruitment_interview_scorecard_template.create', 'hr.recruitment_interview_scorecard_template.update', 'hr.recruitment_interview_scorecard_template.delete',
                'hr.recruitment_selection_review.view_any', 'hr.recruitment_selection_review.view', 'hr.recruitment_selection_review.create', 'hr.recruitment_selection_review.update', 'hr.recruitment_selection_review.delete', 'hr.recruitment_selection_review.approve',
                'hr.recruitment_offer.view_any', 'hr.recruitment_offer.view', 'hr.recruitment_offer.create', 'hr.recruitment_offer.update', 'hr.recruitment_offer.delete', 'hr.recruitment_offer.approve', 'hr.recruitment_offer.issue', 'hr.recruitment_offer.withdraw',
                'hr.recruitment_pre_employment_check.view_any', 'hr.recruitment_pre_employment_check.view', 'hr.recruitment_pre_employment_check.create', 'hr.recruitment_pre_employment_check.update', 'hr.recruitment_pre_employment_check.delete', 'hr.recruitment_pre_employment_check.view_confidential', 'hr.recruitment_pre_employment_check.waive',
                'hr.recruitment_hire.convert',
                'hr.recruitment_onboarding_template.view_any', 'hr.recruitment_onboarding_template.view', 'hr.recruitment_onboarding_template.create', 'hr.recruitment_onboarding_template.update', 'hr.recruitment_onboarding_template.delete',
                'hr.recruitment_onboarding_plan.view_any', 'hr.recruitment_onboarding_plan.view', 'hr.recruitment_onboarding_plan.create', 'hr.recruitment_onboarding_plan.update', 'hr.recruitment_onboarding_plan.delete',
                'hr.recruitment_onboarding_task.view_any', 'hr.recruitment_onboarding_task.view', 'hr.recruitment_onboarding_task.create', 'hr.recruitment_onboarding_task.update', 'hr.recruitment_onboarding_task.delete', 'hr.recruitment_onboarding_task.complete', 'hr.recruitment_onboarding_task.approve', 'hr.recruitment_onboarding_task.waive',
                'hr.employee_confirmation_decision.view_any', 'hr.employee_confirmation_decision.view', 'hr.employee_confirmation_decision.create', 'hr.employee_confirmation_decision.update', 'hr.employee_confirmation_decision.delete', 'hr.employee_confirmation_decision.approve', 'hr.employee_confirmation_decision.implement',
                'hr.recruitment_report.view', 'hr.recruitment_report.export', 'hr.recruitment_history.view',
                'hr.team_recruitment.view', 'hr.team_recruitment.review',
                'hr.my_onboarding.view', 'hr.my_onboarding.update', 'hr.my_probation_status.view', 'hr.my_confirmation_status.view',
                'payroll.attendance_batch.view_any', 'payroll.attendance_batch.view', 'payroll.attendance_batch.create', 'payroll.attendance_batch.update', 'payroll.attendance_batch.delete',
                'payroll.attendance_batch.generate', 'payroll.attendance_batch.submit', 'payroll.attendance_batch.approve', 'payroll.attendance_batch.reject', 'payroll.attendance_batch.post', 'payroll.attendance_batch.reverse',
                'payroll.attendance_adjustment.view_any', 'payroll.attendance_adjustment.view', 'payroll.attendance_adjustment.create', 'payroll.attendance_adjustment.update',
                'payroll.attendance_adjustment.override', 'payroll.attendance_adjustment.reverse',
                'payroll.attendance_rule.view_any', 'payroll.attendance_rule.view', 'payroll.attendance_rule.create', 'payroll.attendance_rule.update',
                'hr.payroll_period.view_any', 'hr.payroll_period.view', 'hr.payroll_period.create', 'hr.payroll_period.update', 'hr.payroll_period.delete',
                'hr.payroll_document.view_any', 'hr.payroll_document.view', 'hr.payroll_document.create', 'hr.payroll_document.update', 'hr.payroll_document.delete',
                'hr.employee_payslip.view_any', 'hr.employee_payslip.view', 'hr.employee_payslip.generate', 'hr.employee_payslip.download', 'hr.employee_payslip.print',
                'hr.employee_payslip.revoke', 'hr.employee_payslip.regenerate', 'hr.employee_payslip.export',
                'hr.employee_payslip_history.view_any', 'hr.employee_payslip_history.view',
                'hr.leave_type.view_any', 'hr.leave_type.view', 'hr.leave_type.create', 'hr.leave_type.update', 'hr.leave_type.delete',
                'hr.leave_policy.view_any', 'hr.leave_policy.view', 'hr.leave_policy.create', 'hr.leave_policy.update', 'hr.leave_policy.delete',
                'hr.leave_entitlement.view_any', 'hr.leave_entitlement.view', 'hr.leave_entitlement.create', 'hr.leave_entitlement.update', 'hr.leave_entitlement.delete',
                'hr.leave_request.view_any', 'hr.leave_request.view', 'hr.leave_request.create', 'hr.leave_request.update', 'hr.leave_request.submit', 'hr.leave_request.cancel',
                'hr.leave_approval.approve', 'hr.leave_approval.reject',
                'hr.leave_balance.view', 'hr.leave_ledger.view_any', 'hr.leave_ledger.view', 'hr.leave_adjustment.post', 'hr.leave_calendar.view',
                'hr.pay_code.view_any', 'hr.pay_code.view', 'hr.pay_code.create', 'hr.pay_code.update',
                'hr.payroll_posting_group.view_any', 'hr.payroll_posting_group.view', 'hr.payroll_posting_group.create', 'hr.payroll_posting_group.update',
            ],
            'project-manager' => [
                'project.capex_project.view_any', 'project.capex_project.view', 'project.capex_project.create', 'project.capex_project.update',
                'factory.production_order.view_any', 'factory.production_order.view',
                'procurement.purchase_order.view_any', 'procurement.purchase_order.view',
                'finance.payment.view_any', 'finance.payment.view',
            ],
            'service-manager' => [
                'service.maintenance_contract.view_any', 'service.maintenance_contract.view', 'service.maintenance_contract.create', 'service.maintenance_contract.update',
                'service.dispatch.view_any', 'service.dispatch.view', 'service.dispatch.create', 'service.dispatch.update',
            ],
            'business-manager' => [
                'sales.order.view_any', 'sales.order.view', 'sales.order.approve', 'sales.order.post',
                'sales.invoice.view_any', 'sales.invoice.view', 'sales.invoice.post',
                'finance.payment.view_any', 'finance.payment.view',
                'finance.customer_ledger_entry.view_any', 'finance.customer_ledger_entry.view',
                'warehouse.shipment.view_any', 'warehouse.shipment.view',
                'factory.production_order.view_any', 'factory.production_order.view',
                'hr.employee.view_any', 'hr.employee.view',
                'procurement.purchase_order.view_any', 'procurement.purchase_order.view',
                'procurement.purchase_invoice.view_any', 'procurement.purchase_invoice.view',
            ],
            'admin' => ['*'],
            'super_admin' => ['*'],
        ];

        $allPermissions = Permission::query()->pluck('name')->all();

        foreach ($matrix as $roleName => $permissions) {
            $role = Role::query()->where('name', $roleName)->where('guard_name', 'web')->first();

            if (! $role) {
                $role = Role::query()->create(['name' => $roleName, 'guard_name' => 'web']);
            }

            if ($permissions === ['*']) {
                $role->syncPermissions($allPermissions);

                continue;
            }

            $role->syncPermissions($permissions);
        }

        app(PermissionRegistrar::class)->forgetCachedPermissions();
    }
}
