<?php
// database/seeders/VendorSeeder.php

namespace Database\Seeders;

use App\Models\Vendor;
use Illuminate\Database\Seeder;

class VendorSeeder extends Seeder
{
    public function run(): void
    {
        $vendors = [
            [
                'vendor_code' => 'V0001',
                'vendor_name' => 'Alpha Chemicals Ltd',
                'contact_person' => 'John Smith',
                'email' => 'john.smith@alphachem.com',
                'phone' => '+1-555-0101',
                'mobile' => '+1-555-0199',
                'address' => '123 Industrial Parkway, Building 4',
                'city' => 'Houston',
                'state' => 'Texas',
                'postal_code' => '77001',
                'country' => 'USA',
                'tax_id' => 'TX-987654321',
                'payment_terms' => 'Net 30',
                'currency' => 'USD',
                'lead_time_days' => 14,
                'minimum_order_amount' => 500.00,
                'is_active' => true,
                'notes' => 'Preferred supplier for raw chemicals. ISO 9001 certified.',
            ],
            [
                'vendor_code' => 'V0002',
                'vendor_name' => 'Beta Supplies Inc',
                'contact_person' => 'Sarah Johnson',
                'email' => 'sarah.j@betasupplies.com',
                'phone' => '+1-555-0202',
                'mobile' => '+1-555-0299',
                'address' => '456 Commerce Street, Suite 200',
                'city' => 'Chicago',
                'state' => 'Illinois',
                'postal_code' => '60601',
                'country' => 'USA',
                'tax_id' => 'IL-123456789',
                'payment_terms' => 'Net 15',
                'currency' => 'USD',
                'lead_time_days' => 7,
                'minimum_order_amount' => 250.00,
                'is_active' => true,
                'notes' => 'Fast delivery for packaging materials.',
            ],
            [
                'vendor_code' => 'V0003',
                'vendor_name' => 'Gamma International',
                'contact_person' => 'Michael Chen',
                'email' => 'mchen@gammaintl.com',
                'phone' => '+86-21-5550-3030',
                'mobile' => '+86-138-0000-0001',
                'address' => '789 Pudong Avenue, Floor 15',
                'city' => 'Shanghai',
                'state' => null,
                'postal_code' => '200120',
                'country' => 'China',
                'tax_id' => 'CN-91310000XXXXXXXX',
                'payment_terms' => 'Net 60',
                'currency' => 'CNY',
                'lead_time_days' => 45,
                'minimum_order_amount' => 5000.00,
                'is_active' => true,
                'notes' => 'Overseas supplier for specialized equipment. Long lead times but competitive pricing.',
            ],
            [
                'vendor_code' => 'V0004',
                'vendor_name' => 'Delta Packaging Solutions',
                'contact_person' => 'Emily Rodriguez',
                'email' => 'emily.r@deltapack.com',
                'phone' => '+1-555-0404',
                'mobile' => '+1-555-0499',
                'address' => '321 Box Factory Road',
                'city' => 'Phoenix',
                'state' => 'Arizona',
                'postal_code' => '85001',
                'country' => 'USA',
                'tax_id' => 'AZ-456789123',
                'payment_terms' => 'Net 30',
                'currency' => 'USD',
                'lead_time_days' => 10,
                'minimum_order_amount' => 100.00,
                'is_active' => true,
                'notes' => 'Custom packaging solutions. Eco-friendly options available.',
            ],
            [
                'vendor_code' => 'V0005',
                'vendor_name' => 'Epsilon Raw Materials',
                'contact_person' => 'Robert Williams',
                'email' => 'r.williams@epsilonraw.com',
                'phone' => '+1-555-0505',
                'mobile' => '+1-555-0599',
                'address' => '159 Mine Road, Industrial Zone',
                'city' => 'Denver',
                'state' => 'Colorado',
                'postal_code' => '80201',
                'country' => 'USA',
                'tax_id' => 'CO-789123456',
                'payment_terms' => 'Net 45',
                'currency' => 'USD',
                'lead_time_days' => 21,
                'minimum_order_amount' => 1000.00,
                'is_active' => true,
                'notes' => 'Bulk raw material supplier. Volume discounts available.',
            ],
            [
                'vendor_code' => 'V0006',
                'vendor_name' => 'Zeta European Imports',
                'contact_person' => 'Anna Schmidt',
                'email' => 'anna.schmidt@zetaimports.eu',
                'phone' => '+49-30-5550-6060',
                'mobile' => '+49-170-0000-0002',
                'address' => 'Hauptstraße 42',
                'city' => 'Berlin',
                'state' => null,
                'postal_code' => '10115',
                'country' => 'Germany',
                'tax_id' => 'DE-123456789012',
                'payment_terms' => 'Net 30',
                'currency' => 'EUR',
                'lead_time_days' => 30,
                'minimum_order_amount' => 2000.00,
                'is_active' => true,
                'notes' => 'Premium European quality products. Higher cost but excellent quality.',
            ],
            [
                'vendor_code' => 'V0007',
                'vendor_name' => 'Eta Logistics & Supply',
                'contact_person' => 'David Kim',
                'email' => 'david.kim@etalogistics.com',
                'phone' => '+1-555-0707',
                'mobile' => '+1-555-0799',
                'address' => '753 Distribution Center Blvd',
                'city' => 'Atlanta',
                'state' => 'Georgia',
                'postal_code' => '30301',
                'country' => 'USA',
                'tax_id' => 'GA-321654987',
                'payment_terms' => 'Net 15',
                'currency' => 'USD',
                'lead_time_days' => 5,
                'minimum_order_amount' => 100.00,
                'is_active' => true,
                'notes' => 'Emergency supplier for rush orders. Premium pricing for speed.',
            ],
            [
                'vendor_code' => 'V0008',
                'vendor_name' => 'Theta Scientific Supplies',
                'contact_person' => 'Dr. Lisa Anderson',
                'email' => 'l.anderson@thetasci.com',
                'phone' => '+1-555-0808',
                'mobile' => '+1-555-0899',
                'address' => '951 Research Park Drive',
                'city' => 'Boston',
                'state' => 'Massachusetts',
                'postal_code' => '02101',
                'country' => 'USA',
                'tax_id' => 'MA-654321789',
                'payment_terms' => 'Net 30',
                'currency' => 'USD',
                'lead_time_days' => 12,
                'minimum_order_amount' => 750.00,
                'is_active' => true,
                'notes' => 'Laboratory grade materials. Certification documentation provided.',
            ],
            [
                'vendor_code' => 'V0009',
                'vendor_name' => 'Iota Wholesale Distributors',
                'contact_person' => 'James Brown',
                'email' => 'jbrown@iotawholesale.com',
                'phone' => '+1-555-0909',
                'mobile' => '+1-555-0999',
                'address' => '357 Bulk Buy Lane',
                'city' => 'Dallas',
                'state' => 'Texas',
                'postal_code' => '75201',
                'country' => 'USA',
                'tax_id' => 'TX-147258369',
                'payment_terms' => 'Net 60',
                'currency' => 'USD',
                'lead_time_days' => 18,
                'minimum_order_amount' => 2500.00,
                'is_active' => true,
                'notes' => 'Wholesale pricing for high volume orders. Limited product range.',
            ],
            [
                'vendor_code' => 'V0010',
                'vendor_name' => 'Kappa Specialty Chemicals',
                'contact_person' => 'Maria Garcia',
                'email' => 'm.garcia@kappachem.com',
                'phone' => '+1-555-1010',
                'mobile' => '+1-555-1099',
                'address' => '246 Specialty Blvd',
                'city' => 'San Diego',
                'state' => 'California',
                'postal_code' => '92101',
                'country' => 'USA',
                'tax_id' => 'CA-369258147',
                'payment_terms' => 'Net 30',
                'currency' => 'USD',
                'lead_time_days' => 28,
                'minimum_order_amount' => 1500.00,
                'is_active' => true,
                'notes' => 'Rare and specialty chemicals. Exclusive distribution rights.',
            ],
            // Inactive vendor for testing
            [
                'vendor_code' => 'V0011',
                'vendor_name' => 'Lambda Discontinued Supplies',
                'contact_person' => 'Inactive Contact',
                'email' => 'inactive@lambda.com',
                'phone' => '+1-555-1111',
                'mobile' => null,
                'address' => '999 Closed Street',
                'city' => 'Detroit',
                'state' => 'Michigan',
                'postal_code' => '48201',
                'country' => 'USA',
                'tax_id' => 'MI-000000000',
                'payment_terms' => 'Net 30',
                'currency' => 'USD',
                'lead_time_days' => null,
                'minimum_order_amount' => null,
                'is_active' => false,
                'notes' => 'Vendor no longer active. Keep for historical records only.',
            ],
        ];

        foreach ($vendors as $vendor) {
            Vendor::firstOrCreate(
                ['vendor_code' => $vendor['vendor_code']],
                $vendor
            );
        }

        $this->command->info('Vendors seeded successfully!');
        $this->command->info('Total: ' . count($vendors) . ' vendors');
        $this->command->info('Active: ' . collect($vendors)->where('is_active', true)->count());
        $this->command->info('Inactive: ' . collect($vendors)->where('is_active', false)->count());
    }
}
