<?php

declare(strict_types=1);

namespace App\Filament\Resources\Manufacturing\ProductionSchedules\Schemas;

use Filament\Infolists\Components\IconEntry;
use Filament\Infolists\Components\TextEntry;
use Filament\Schemas\Components\Grid;
use Filament\Schemas\Components\Section;
use Filament\Schemas\Schema;

class ProductionScheduleInfolist
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                Grid::make([
                    'default' => 1,
                    'xl' => 2,
                ])->schema([
                    Section::make('Schedule')
                        ->columns(2)
                        ->schema([
                            TextEntry::make('schedule_no')->weight('bold'),
                            TextEntry::make('status')->badge(),
                            TextEntry::make('scheduling_mode')->badge(),
                            TextEntry::make('planning_version'),
                            TextEntry::make('horizon_start_at')->dateTime(),
                            TextEntry::make('horizon_end_at')->dateTime(),
                        ]),
                    Section::make('Planner Summary')
                        ->columns(2)
                        ->schema([
                            TextEntry::make('summary.operations_scheduled')->label('Operations Scheduled'),
                            TextEntry::make('summary.exceptions')->label('Exceptions'),
                            TextEntry::make('summary.late_operations')->label('Late Operations'),
                            TextEntry::make('summary.bottlenecks')->label('Bottlenecks'),
                            IconEntry::make('approved_at')
                                ->label('Approved')
                                ->boolean()
                                ->state(fn ($record): bool => $record->approved_at !== null),
                        ]),
                    Section::make('Audit')
                        ->columns(2)
                        ->collapsible()
                        ->schema([
                            TextEntry::make('generator.name')->label('Generated By'),
                            TextEntry::make('generated_at')->dateTime(),
                            TextEntry::make('approved_at')->dateTime(),
                            TextEntry::make('notes')->columnSpanFull(),
                        ])
                        ->columnSpanFull(),
                ]),
            ]);
    }
}
