<?php

namespace App\Filament\Resources\BlanketOrders\Tables;

use Filament\Actions\BulkActionGroup;
use Filament\Actions\DeleteBulkAction;
use Filament\Actions\EditAction;
use Filament\Actions\ForceDeleteBulkAction;
use Filament\Actions\RestoreBulkAction;
use Filament\Tables\Columns\IconColumn;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Filters\TrashedFilter;
use Filament\Tables\Table;

class BlanketOrdersTable
{
    public static function configure(Table $table): Table
    {
        return $table
            ->columns([
                TextColumn::make('document_number')
                    ->searchable(),
                TextColumn::make('external_document_no')
                    ->searchable(),
                TextColumn::make('vendor.id')
                    ->searchable(),
                TextColumn::make('document_type')
                    ->searchable(),
                TextColumn::make('status')
                    ->searchable(),
                TextColumn::make('posting_date')
                    ->date()
                    ->sortable(),
                TextColumn::make('document_date')
                    ->date()
                    ->sortable(),
                TextColumn::make('order_date')
                    ->date()
                    ->sortable(),
                TextColumn::make('starting_date')
                    ->date()
                    ->sortable(),
                TextColumn::make('ending_date')
                    ->date()
                    ->sortable(),
                TextColumn::make('buyer.name')
                    ->searchable(),
                TextColumn::make('responsibility_center')
                    ->searchable(),
                TextColumn::make('assignedUser.name')
                    ->searchable(),
                TextColumn::make('project_code')
                    ->searchable(),
                TextColumn::make('department_code')
                    ->searchable(),
                TextColumn::make('shortcut_dimension_1_code')
                    ->searchable(),
                TextColumn::make('shortcut_dimension_2_code')
                    ->searchable(),
                TextColumn::make('dimension_set_id')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('vendor_order_no')
                    ->searchable(),
                TextColumn::make('purchase_order_no')
                    ->searchable(),
                TextColumn::make('order_address_code')
                    ->searchable(),
                TextColumn::make('currency_code')
                    ->searchable(),
                TextColumn::make('exchange_rate')
                    ->numeric()
                    ->sortable(),
                IconColumn::make('prices_including_vat')
                    ->boolean(),
                TextColumn::make('payment_terms_code')
                    ->searchable(),
                TextColumn::make('payment_method_code')
                    ->searchable(),
                TextColumn::make('transaction_type')
                    ->searchable(),
                TextColumn::make('transaction_specification')
                    ->searchable(),
                TextColumn::make('transport_method')
                    ->searchable(),
                TextColumn::make('entry_point')
                    ->searchable(),
                TextColumn::make('area')
                    ->searchable(),
                TextColumn::make('language_code')
                    ->searchable(),
                TextColumn::make('format_region')
                    ->searchable(),
                TextColumn::make('buy_from_vendor_name')
                    ->searchable(),
                TextColumn::make('buy_from_address')
                    ->searchable(),
                TextColumn::make('buy_from_address_2')
                    ->searchable(),
                TextColumn::make('buy_from_city')
                    ->searchable(),
                TextColumn::make('buy_from_post_code')
                    ->searchable(),
                TextColumn::make('buy_from_county')
                    ->searchable(),
                TextColumn::make('buy_from_country_region_code')
                    ->searchable(),
                TextColumn::make('buy_from_contact')
                    ->searchable(),
                TextColumn::make('pay_to_vendor_no')
                    ->searchable(),
                TextColumn::make('pay_to_name')
                    ->searchable(),
                TextColumn::make('pay_to_address')
                    ->searchable(),
                TextColumn::make('pay_to_address_2')
                    ->searchable(),
                TextColumn::make('pay_to_city')
                    ->searchable(),
                TextColumn::make('pay_to_post_code')
                    ->searchable(),
                TextColumn::make('pay_to_county')
                    ->searchable(),
                TextColumn::make('pay_to_country_region_code')
                    ->searchable(),
                TextColumn::make('pay_to_contact')
                    ->searchable(),
                TextColumn::make('ship_to_code')
                    ->searchable(),
                TextColumn::make('ship_to_name')
                    ->searchable(),
                TextColumn::make('ship_to_address')
                    ->searchable(),
                TextColumn::make('ship_to_address_2')
                    ->searchable(),
                TextColumn::make('ship_to_city')
                    ->searchable(),
                TextColumn::make('ship_to_post_code')
                    ->searchable(),
                TextColumn::make('ship_to_county')
                    ->searchable(),
                TextColumn::make('ship_to_country_region_code')
                    ->searchable(),
                TextColumn::make('ship_to_contact')
                    ->searchable(),
                TextColumn::make('location_code')
                    ->searchable(),
                TextColumn::make('shipment_method_code')
                    ->searchable(),
                TextColumn::make('shipping_agent_code')
                    ->searchable(),
                TextColumn::make('shipping_agent_service_code')
                    ->searchable(),
                TextColumn::make('package_tracking_no')
                    ->searchable(),
                TextColumn::make('invoice_disc_code')
                    ->searchable(),
                TextColumn::make('requested_receipt_date')
                    ->date()
                    ->sortable(),
                TextColumn::make('promised_receipt_date')
                    ->date()
                    ->sortable(),
                TextColumn::make('quote_no')
                    ->searchable(),
                IconColumn::make('released')
                    ->boolean(),
                TextColumn::make('released_at')
                    ->dateTime()
                    ->sortable(),
                TextColumn::make('released_by')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('created_by')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('last_modified_by')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('created_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                TextColumn::make('updated_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                TextColumn::make('deleted_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->filters([
                TrashedFilter::make(),
            ])
            ->recordActions([
                EditAction::make(),
            ])
            ->toolbarActions([
                BulkActionGroup::make([
                    DeleteBulkAction::make(),
                    ForceDeleteBulkAction::make(),
                    RestoreBulkAction::make(),
                ]),
            ]);
    }
}
