<?php

namespace App\Filament\Resources\PurchaseOrders\Schemas;

use App\Enums\PurchaseOrderStatus;
use App\Enums\PurchaseOrderType;
use App\Models\Vendor;
use Filament\Forms\Components\DatePicker;
use Filament\Forms\Components\DateTimePicker;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\Textarea;
use Filament\Forms\Components\Hidden;
use Filament\Forms\Components\Placeholder;
use Filament\Infolists\Components\TextEntry;
use Filament\Schemas\Components\Grid;
use Filament\Schemas\Components\Section;
use Filament\Schemas\Schema;

class PurchaseOrderForm
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                Section::make('Order Header')
                    ->description('Define the type, vendor, and general order information.')
                    ->schema([
                        Grid::make(3)->schema([
                            Select::make('order_type')
                                ->label('Order Type')
                                // Use Enum options method directly
                                ->options(PurchaseOrderType::options())
                                ->default('purchase_order')
                                ->required()
                                ->live()
                                ->afterStateUpdated(fn ($state, callable $set) =>
                                    // Auto-generate a preview if number is empty (optional UX enhancement)
                                $set('order_number_preview', PurchaseOrderType::from($state)?->seriesCode() . '-AUTO')
                                ),

                            TextInput::make('order_number')
                                ->label('Order Number')
                                ->unique(ignoreRecord: true)
                                // Hint that it might be auto-generated by the Model
                                ->helperText('Leave blank to auto-generate based on Series.')
                                ->disabled(fn ($context) => $context === 'create'), // Optional: Disable on create to force auto-gen, or leave enabled for override

                            Select::make('vendor_id')
                                ->label('Vendor')
                                ->relationship('vendor', 'vendor_name')
                                ->searchable()
                                ->preload()
                                ->required()
                                ->live()
                                ->afterStateUpdated(function ($state, callable $set) {
                                    if ($state) {
                                        $vendor = Vendor::find($state);
                                        $set('vendor_name', $vendor?->vendor_name ?? '');
                                        $set('payment_terms', $vendor?->payment_terms ?? '');
                                    } else {
                                        $set('vendor_name', '');
                                        $set('payment_terms', '');
                                    }
                                }),

                            Select::make('location_id')
                                ->label('Ship To Location')
                                ->relationship('location', 'location_name')
                                ->searchable()
                                ->preload()
                                ->required(),

                            DatePicker::make('order_date')
                                ->label('Order Date')
                                ->required()
                                ->default(now())
                                ->native(false),

                            Select::make('status')
                                ->label('Status')
                                ->options(PurchaseOrderStatus::options())
                                ->default('PENDING')
                                ->required()
                                ->disabled(fn ($record) => !$record?->canEdit), // Disable if model says not editable
                        ]),

                        // Store the vendor name denormalized field, hidden from user interaction or read-only
                        TextInput::make('vendor_name')
                            ->label('Vendor Name (Denormalized)')
                            ->required()
                            ->disabled() // Populated by the vendor_id selection
                            ->dehydrated(true), // Ensure it saves to DB
                    ]),

                Section::make('Dates & Terms')
                    ->schema([
                        Grid::make(3)->schema([
                            DatePicker::make('due_date')
                                ->label('Due Date')
                                ->native(false),

                            DatePicker::make('delivery_date')
                                ->label('Expected Delivery')
                                ->native(false),

                            DatePicker::make('posting_date')
                                ->label('Posting Date')
                                ->native(false),

                            TextInput::make('payment_terms')
                                ->label('Payment Terms')
                                ->maxLength(50),
                        ])
                    ])
                    ->columns(2),

                Section::make('Financials')
                    ->description('Order totals. These are typically calculated from line items.')
                    ->schema([
                        Grid::make(3)->schema([
                            TextInput::make('total_amount')
                                ->label('Total Amount (Excl. VAT)')
                                ->required()
                                ->numeric()
                                ->prefix('$')
                                ->default(0)
                                ->disabled(fn ($record) => $record && $record->id !== null), // Read-only on edit if calculated by lines

                            TextInput::make('total_vat')
                                ->label('Total VAT')
                                ->required()
                                ->numeric()
                                ->prefix('$')
                                ->default(0)
                                ->disabled(fn ($record) => $record && $record->id !== null),

                            TextInput::make('grand_total')
                                ->label('Grand Total')
                                ->required()
                                ->numeric()
                                ->prefix('$')
                                ->default(0)
                                ->disabled(fn ($record) => $record && $record->id !== null),
                        ]),

                        // Visual helper for calculated Grand Total
                        Placeholder::make('total_preview')
                            ->label('Grand Total Preview')
                            ->content(function ($get) {
                                $amount = (float) $get('total_amount');
                                $vat = (float) $get('total_vat');
                                return '$' . number_format($amount + $vat, 4);
                            })
                            ->visible(fn ($context) => $context === 'create'),
                    ])
                    ->columns(2),

                Section::make('Approval')
                    ->schema([
                        Grid::make(2)->schema([
                            Select::make('approved_by')
                                ->label('Approved By')
                                ->relationship('approver', 'name')
                                ->searchable()
                                ->preload()
                                ->visible(fn ($record) => $record && $record->status !== PurchaseOrderStatus::PENDING),

                            DateTimePicker::make('approved_at')
                                ->label('Approved At')
                                ->seconds(false)
                                ->disabled()
                                ->visible(fn ($record) => $record && !is_null($record->approved_at)),
                        ])
                    ])
                    ->collapsible()
                    ->visible(fn ($record) => $record !== null), // Only show in Edit mode

                Section::make('Notes')
                    ->schema([
                        Textarea::make('comment')
                            ->label('Comments / Internal Notes')
                            ->rows(3)
                            ->columnSpanFull(),
                    ]),

                Hidden::make('created_by')
                    ->default(auth()->id()),
            ]);
    }
}
